name: Trigger Men Clothes Pipeline

on:
    workflow_dispatch:  
      inputs:
          infile:
              description: 'The input CSV file path'
              default: 'private_repo/clean_data/men_clothing/to_create.csv'
          outfile:
              description: 'Where to store non-existent products'
              default: 'private_repo/clean_data/men_clothing/skus_to_add.csv'
          all_data_file:
              description: 'All cleaned dataset'
              default: 'private_repo/clean_data/men_clothing/to_create.csv'
          to_update:
            description: 'Products to update'
            default: 'private_repo/clean_data/men_clothing/to_update.csv'
          zero_inventory:
            description: 'Zero Inventory dataset'
            default: 'private_repo/clean_data/men_clothing/zero_inventory.csv'


jobs:
  trigger-public-workflow:
    runs-on: ubuntu-latest

    permissions:
        contents: write  
        packages: write  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
    
      - name: Set up environment and run script with secrets
        run: |
            echo "Setting up environment variables"
        env:
            SUPPLIER_URL: ${{ secrets.SUPPLIER_URL }}
            LOGIN: ${{ secrets.LOGIN }}
            PASSWORD: ${{ secrets.PASSWORD }}

      - name: Clone Private Repository
        run: |
          git clone https://${{ secrets.PROFILE_URL }}:${{secrets.PUBLIC_PAT}}@github.com/${{ secrets.PROFILE_URL_REPO }}.git private_repo
     
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        run: pip install pandas requests lxml selenium argparse

      - name: Scrape data
        run: |
            echo "Scraping data and generating CSV..."
            export SUPPLIER_URL="${{ secrets.SUPPLIER_URL }}"
            export LOGIN="${{ secrets.LOGIN }}"
            export PASSWORD="${{ secrets.PASSWORD }}"
            python /home/runner/work/supplier3_unified_scraper/supplier3_unified_scraper/get_data.py \
                        --filename "men_clothing.csv" \
                        --pages "1,11" "12,23" "24,35" "36,47" "48,59" "60,71" \
                        --urls "${{ secrets.MEN_CLOTHES }}" \
                        --n_collections=6 --max_workers=6

      - name: Clean Data
        run: |
            python /home/runner/work/supplier3_unified_scraper/supplier3_unified_scraper/private_repo/clean_men_clothing.py --input_file "men_clothing.csv"

      - name: Install Node.js dependencies 
        run: npm install axios csv-parser dotenv shopify-api-node fs
    
      - name: Check existing SKUs
        run: node /home/runner/work/supplier3_unified_scraper/supplier3_unified_scraper/check_existing_skus.js
        env:
            SHOP: ${{ secrets.SHOP }}
            SHOPIFY_ACCESS_TOKEN: ${{ secrets.SHOPIFY_ACCESS_TOKEN_MEN_CLOTHES }}
            INFILE: 'private_repo/clean_data/men_clothing/to_create.csv'
            OUTFILE: 'private_repo/clean_data/men_clothing/skus_to_add.csv'

      - name: Add new products
        run: node /home/runner/work/supplier3_unified_scraper/supplier3_unified_scraper/add_products.js
        env:
            SHOP: ${{ secrets.SHOP }}
            SHOPIFY_ACCESS_TOKEN: ${{ secrets.SHOPIFY_ACCESS_TOKEN_MEN_CLOTHES }}
            ALL_DATA_FILE: 'private_repo/clean_data/men_clothing/to_create.csv'
            OUTFILE: 'private_repo/clean_data/men_clothing/skus_to_add.csv'

      - name: Update products
        run: node /home/runner/work/supplier3_unified_scraper/supplier3_unified_scraper/update_products.js
        env:
            SHOP: ${{ secrets.SHOP }}
            SHOPIFY_ACCESS_TOKEN: ${{ secrets.SHOPIFY_ACCESS_TOKEN_MEN_CLOTHES }}
            TO_UPDATE: 'private_repo/clean_data/men_clothing/to_update.csv'

      - name: Update products
        run: node /home/runner/work/supplier3_unified_scraper/supplier3_unified_scraper/set_zero_inventory.js
        env:
            SHOP: ${{ secrets.SHOP }}
            SHOPIFY_ACCESS_TOKEN: ${{ secrets.SHOPIFY_ACCESS_TOKEN_MEN_CLOTHES }}
            ZERO_INVENTORY: 'private_repo/clean_data/men_clothing/zero_inventory.csv'
                    
      - name: Commit changes from update.py
        run: |
            cd private_repo
            git config --local user.name "GitHub Action"
            git config --local user.email "action@github.com"
            git pull origin master --no-edit
            git add .
            git commit -m "Commit changes from update.py"
            git push
          