name: Trigger Men Sunglasses Pipeline

on:
  workflow_dispatch:  

  schedule:
    - cron: '0 */6 * * *'  

jobs:
  trigger-public-workflow:
    runs-on: ubuntu-latest

    permissions:
        contents: write  
        packages: write  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
    
      - name: Set up environment and run script with secrets
        run: |
            echo "Setting up environment variables"
        env:
            SUPPLIER_URL: ${{ secrets.SUPPLIER_URL }}
            LOGIN: ${{ secrets.LOGIN }}
            PASSWORD: ${{ secrets.PASSWORD }}

      - name: Clone Private Repository
        run: |
          git clone https://${{ secrets.PROFILE_URL }}:${{secrets.PUBLIC_PAT}}@github.com/${{ secrets.PROFILE_URL_REPO }}.git private_repo
     
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        run: pip install pandas requests lxml selenium argparse

      - name: Scrape data
        run: |
            echo "Scraping data and generating CSV..."
            export SUPPLIER_URL="${{ secrets.SUPPLIER_URL }}"
            export LOGIN="${{ secrets.LOGIN }}"
            export PASSWORD="${{ secrets.PASSWORD }}"
            python /home/runner/work/supplier3_unified_scraper/supplier3_unified_scraper/get_data.py \
                        --filename "men_sunglasses.csv" \
                        --pages "1,5" \
                        --urls "${{ secrets.MEN_SUNGLASSES }}" \
                        --n_collections=1 --max_workers=1

      - name: Clean Data
        run: |
            python /home/runner/work/supplier3_unified_scraper/supplier3_unified_scraper/private_repo/clean_sunglasses.py --input_file "men_sunglasses.csv"

      - name: Install Node.js dependencies 
        run: npm install axios csv-parser dotenv shopify-api-node fs
    
      - name: Check existing SKUs
        run: node /home/runner/work/supplier3_unified_scraper/supplier3_unified_scraper/check_existing_skus.js
        env:
          SHOP: ${{ secrets.SHOP }}
          SHOPIFY_ACCESS_TOKEN: ${{ secrets.SHOPIFY_ACCESS_TOKEN }}
          INFILE: 'private_repo/clean_data/sunglasses/clean_sunglasses.csv'
          OUTFILE: 'private_repo/clean_data/sunglasses/skus_to_add.csv'

      - name: Add new products
        run: node /home/runner/work/supplier3_unified_scraper/supplier3_unified_scraper/add_products.js
        env:
            SHOP: ${{ secrets.SHOP }}
            SHOPIFY_ACCESS_TOKEN: ${{ secrets.SHOPIFY_ACCESS_TOKEN }}
            ALL_DATA_FILE: 'private_repo/clean_data/sunglasses/clean_sunglasses.csv'
            OUTFILE: 'private_repo/clean_data/sunglasses/skus_to_add.csv'
    
      - name: Update products
        run: node /home/runner/work/supplier3_unified_scraper/supplier3_unified_scraper/update_products.js
        env:
            SHOP: ${{ secrets.SHOP }}
            SHOPIFY_ACCESS_TOKEN: ${{ secrets.SHOPIFY_ACCESS_TOKEN }}
            TO_UPDATE: 'private_repo/clean_data/sunglasses/clean_sunglasses.csv'

      - name: Set Inventory Zero
        run: node /home/runner/work/supplier3_unified_scraper/supplier3_unified_scraper/set_zero_inventory.js
        env:
            SHOP: ${{ secrets.SHOP }}
            SHOPIFY_ACCESS_TOKEN: ${{ secrets.SHOPIFY_ACCESS_TOKEN }}
            ZERO_INVENTORY:  'private_repo/clean_data/sunglasses/zero_inventory.csv'
            

      - name: Commit changes 
        run: |
          cd private_repo
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git pull origin master --no-edit
          git add clean_data/sunglasses/
          git diff --cached --quiet || git commit -m "Commit changes from actions"
          git push
      