name: Trigger Women Clothes (Part 3) Pipeline

on:
    workflow_dispatch:  

    # schedule:
    # - cron: '0 */4 * * *'  

jobs:
  trigger-public-workflow:
    runs-on: ubuntu-latest

    permissions:
        contents: write  
        packages: write  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
    
      - name: Set up environment and run script with secrets
        run: |
            echo "Setting up environment variables"
        env:
            SUPPLIER_URL: ${{ secrets.SUPPLIER_URL }}
            LOGIN: ${{ secrets.LOGIN }}
            PASSWORD: ${{ secrets.PASSWORD }}

      - name: Clone Private Repository
        run: |
          git clone https://${{ secrets.PROFILE_URL }}:${{secrets.PUBLIC_PAT}}@github.com/${{ secrets.PROFILE_URL_REPO }}.git private_repo
     
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        run: pip install pandas requests lxml selenium argparse

      - name: Scrape data
        run: |
            echo "Scraping data and generating CSV..."
            export SUPPLIER_URL="${{ secrets.SUPPLIER_URL }}"
            export LOGIN="${{ secrets.LOGIN }}"
            export PASSWORD="${{ secrets.PASSWORD }}"
            python /home/runner/work/supplier3_unified_scraper/supplier3_unified_scraper/get_data.py \
                        --filename "women_clothing_part3.csv" \
                        --pages "91,100" "101,110" "111,120" "121,130" "131,140" "141,150" "151,160" \
                        --urls "${{ secrets.WOMEN_CLOTHES }}" \
                        --n_collections=7 --max_workers=6

      - name: Commit changes from update.py
        run: |
          cd private_repo
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git pull origin master --no-edit
          git add clean_data/women_clothing/
          git commit -m "Commit changes from update.py"
          git push
                      

      - name: Clean Data
        run: |
            python /home/runner/work/supplier3_unified_scraper/supplier3_unified_scraper/private_repo/clean_women_clothing.py --input_file "women_clothing_part3.csv"

      - name: Install Node.js dependencies 
        run: npm install axios csv-parser dotenv shopify-api-node fs
        
      - name: Check existing SKUs
        run: node /home/runner/work/supplier3_unified_scraper/supplier3_unified_scraper/check_existing_skus.js
        env:
            SHOP: ${{ secrets.SHOP }}
            SHOPIFY_ACCESS_TOKEN: ${{ secrets.SHOPIFY_ACCESS_TOKEN }}
            INFILE: 'private_repo/clean_data/women_clothing/to_create.csv'
            OUTFILE: 'private_repo/clean_data/women_clothing/skus_to_add.csv'

      - name: Add new products
        run: node /home/runner/work/supplier3_unified_scraper/supplier3_unified_scraper/add_products.js
        env:
            SHOP: ${{ secrets.SHOP }}
            SHOPIFY_ACCESS_TOKEN: ${{ secrets.SHOPIFY_ACCESS_TOKEN }}
            ALL_DATA_FILE: 'private_repo/clean_data/women_clothing/to_create.csv'
            OUTFILE: 'private_repo/clean_data/women_clothing/skus_to_add.csv'

      - name: Update products
        run: node /home/runner/work/supplier3_unified_scraper/supplier3_unified_scraper/update_products.js
        env:
            SHOP: ${{ secrets.SHOP }}
            SHOPIFY_ACCESS_TOKEN: ${{ secrets.SHOPIFY_ACCESS_TOKEN }}
            TO_UPDATE: 'private_repo/clean_data/women_clothing/to_update.csv'

      - name: Update products
        run: node /home/runner/work/supplier3_unified_scraper/supplier3_unified_scraper/set_zero_inventory.js
        env:
            SHOP: ${{ secrets.SHOP }}
            SHOPIFY_ACCESS_TOKEN: ${{ secrets.SHOPIFY_ACCESS_TOKEN }}
            ZERO_INVENTORY: 'private_repo/clean_data/women_clothing/zero_inventory.csv'

      - name: Commit changes from update.py
        run: |
          cd private_repo
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git pull origin master --no-edit
          git add clean_data/women_clothing/
          git diff --cached --quiet || git commit -m "Commit changes from actions"
          git push
      
